# Generated by Django 5.1.1 on 2024-09-21 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_genre_alter_book_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Created time'),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Numbers of books'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Last Update Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=250, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Book Title'),
        ),
    ]
