# Generated by Django 5.1.1 on 2024-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_delete_genre_remove_book_price_author_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=250, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author_country'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
